### ISSUE TITLE
Schema Modifications

### ISSUE THREAD

**Issue by nivykani** [white-van/discussion-board#22]
### What problem are you facing?

Currently, a post can only be authored by one user. If two students think of a post idea together, the upvotes will only go to the user that made the post.

### How could Pizza help solve your problem?

It would be nice if a post can be co-authored by multiple users (e.g. someone asks a question on behalf of their team) and then all upvotes/awards/reply notifications/etc. apply to all authors of that post.

**Comment by krishchow** [comment]
thanks @NivedithaK :D 

Some other notes for revisions to the schema:

- We need a spot for an auth code, and an auth period - this will allow students to join a course, and after some amount of time, students can no longer be added to a course. Alternatively, we may want users to be added via email, in which case things get a bit trickier.

**Comment by krishchow** [comment]
@juanjaramillogar Feel free to leave any notes here
